# Generated by Django 5.1.4 on 2025-01-09 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitnessgoal',
            name='user',
        ),
    ]
